// src/app/components/ThirdHeader/ThirdHeader.tsx
import React from "react";
import Button from "../Button/Button";
import styles from "./ThirdHeader.module.scss";

const ThirdHeader = () => {
	return (
		<div className={styles.ThirdHeader}>
			<div className={styles.Container}>
				<div className={styles.ImageContainer}>
					<img className={styles.BentoAsset} src={"images/assets_upstanding.png"} alt="Header Image" />
				</div>
				<div className={styles.ContainerInner}>
					<div className={styles.Content}>
						<div className={styles.Heading}>Faites concevoir votre site web par des professionnels</div>
						<div className={styles.Text}>Mon agence est spécialisée dans la création de sites web de haute qualité pour les propriétaires de petites entreprises. Grâce à mon expertise et mon souci du détail, je garantie un site non seulement esthétiquement attrayant, mais aussi facile à utiliser et optimisé pour les moteurs de recherche.</div>
					</div>
					<div className={styles.Actions}>
						<Button style="primary">Contactez-moi</Button>
						<Button style="secondary">Voir mon travail</Button>
					</div>
				</div>
			</div>
		</div>
	);
};

export default ThirdHeader;

// src/routes/ThirdHeader.svelte
<script>
  // Import the Button component
  import Button from '../Button.svelte';
  import bentoAsset from '$lib/images/assets upstanding.png'
</script>

<div class="ThirdHeader">
  <div class="Container">
    <div class="ImageContainer">
      <img class="BentoAsset" src={bentoAsset} alt="Header dImage" />
    </div>
    <div class="Container">
      <div class="Content">
        <div class="Heading">Faites concevoir votre site web par des professionnels</div>
        <div class="Text">Mon agence est spécialisée dans la création de sites web de haute qualité pour les propriétaires de petites entreprises. Grâce à mon expertise et mon souci du détail, je garantie un site non seulement esthétiquement attrayant, mais aussi facile à utiliser et optimisé pour les moteurs de recherche.</div>
      </div>
      <div class="Actions">
        <Button style="primary">Contactez-moi</Button>
        <Button style="secondary">Voir mon travail</Button>
      </div>
    </div>
  </div>
</div>

<style lang="scss">
  .ThirdHeader {
    width: 100vw;
    height: 843px;
    padding: 112px 64px;
    display: inline-flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
    gap: 80px;

    .Container {
      align-self: stretch;
      display: inline-flex;
      justify-content: flex-start;
      align-items: center;
      gap: 80px;

      .ImageContainer {
        height: 619px;
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 10px;

        .BentoAsset {
          width: 304px;
          height: 619px;
        }
      }

      .Content {
        flex: 1 1 0;
        display: inline-flex;
        flex-direction: column;
        justify-content: flex-start;
        align-items: flex-start;
        gap: 24px;

        .Heading {
          align-self: stretch;
          color: white;
          font-size: 48px;
          font-family: Poppins, sans-serif;
          font-weight: 700;
          line-height: 57.60px;
          word-wrap: break-word;
        }

        .Text {
          align-self: stretch;
          color: white;
          font-size: 18px;
          font-family: Acme, sans-serif;
          font-weight: 400;
          line-height: 27px;
          word-wrap: break-word;
        }
      }
    }
  }

  @media (max-width: 767px) {
    .ThirdHeader {
      width: 100vw;
      height: 778px;
      padding: 28px 22px;
      gap: 80px;

      .Container {
        height: 722px;
        flex-direction: column;
        justify-content: center;
        align-items: flex-start;
        gap: 22px;

        .ImageContainer {
          align-self: stretch;
          display: inline-flex;
          justify-content: center;
          align-items: center;

          .BentoAsset {
            width: 117px;
            height: 255px;
          }
        }

        .Content {
          align-self: stretch;
          height: 269px;
          display: flex;
          flex-direction: column;
          justify-content: flex-start;
          align-items: flex-start;
          gap: 14px;

          .Heading {
            font-size: 24px;
            line-height: 28.80px;
          }

          .Text {
            font-size: 12px;
            line-height: 18px;
          }
        }
      }
    }
  }
</style>
